### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by signmeuptwice** [jcampbell1/simple-file-manager#60]
First time user, I would like to use SFM for an admin page.

When I launch the file I get Failed to load resource: the server responded with a status of 403 (Forbidden)

{"error":{"code":403,"msg":"XSRF Failure"}}

What could this be please ?

Is there a setup tutorial somewhere ? The information provided on the Github page are not enough for me to understand. It only says to copy the index.php file

**Comment by czmole** [comment]
Wondering: how do you include it in that admin page?

**Comment by ParkerD13** [comment]
Had the same problem and just in case some else stumbles upon this:
I had to buffer the output or otherwise `setcookie('_sfm_xsrf',bin2hex(openssl_random_pseudo_bytes(16)));` does not work. I included my config at the head of the file and that screwed it up. So I put [ob_start()](https://www.php.net/manual/de/function.ob-start.php) at the beginning of the script and [ob_flush()](https://www.php.net/manual/de/function.ob-flush.php) after the cookie is set. Hope that helps.
